### ISSUE TITLE
Add option to subscribe multiple validators at once #83

### ISSUE THREAD

**Issue by mateodaza** [dappnode/mev-sp-fe#3]
Context:
* Currently validators can only be subscribed one by one. Meaning that someone with 50, would need to send 50 different txs, which implies: click Subscribe button, sign tx, wait, repeat. Not the best UX.

Feture:
* Add new button with `Subscribe All` that allows to subscribe all validators that are in `notsubscribed` or `untracked` state.

Tasks:
- [x] Update the abi to the latest. Latest can be found [here](https://github.com/dappnode/mev-sp-oracle/blob/main/contract/abi.abi). Its important to have this latest abi because it adds the `subscribeValidators` function.
- [x] Create new button named `Subscribe All`. No opinion where it should be placed.
- [x] When `Subscribe All` button is clicked, get all validators belonging to the connected wallet `/memory/validators/0x_wallet` (note that this is already being done) and **filter** all validators so that we get the ones in `notsubscribed` or `untracked` state. This is very important as it wouldn't make sense to subscribe an already subscribed validator. Then, get their `validator_index` eg: `validator_index(es)=5, 10, 40, 60`.
- [ ] Call the function `subscribeValidators` with said indexes and payable amount equal to `collateral_in_wei` * `length(indexes)`. As a reminder `collateral_in_wei` is already used by the contract and can be fetched from `:7300/config`

Note: `subscribeValidators` function is very similar to `subscribeValidator` with the only difference that it takes an array of validators, and that the collateral amount has to be x times the amount of validators, where x is the amount of validators one wants to subscribe.

**Comment by mateodaza** [comment]
`from old repo >>>>`

<img width="1058" alt="image" src="https://github.com/dappnode/mev-sp-fe/assets/18689480/69c64769-faf6-4654-80e5-c7343005f76f">

**Comment by Pol-Lanski** [comment]
To @eduadiez 's point of how slow it is, we can use 2 mitigations:

1. change the check so it's the front-end who does it instead of the Oracle. This will avoid the oracle getting rate limited even if just a few people with a few validators try to check at the same time.
2. Warn the user that it might take a while and put a `n/m` completion indicator as in the image below:

<img width="529" alt="Screenshot 2023-11-17 at 10 04 35" src="https://github.com/dappnode/mev-sp-fe/assets/19168735/557583d8-cdb8-4204-9a5f-c278e3a3408d">
